name: build-tag-push

on: push

jobs:

  build-tag-push:
    name: "Build tag and push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion
      
      - uses: docker/setup-buildx-action@v2        

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            voortman/talos-os-config-generator:latest
            voortman/talos-os-config-generator:${{ steps.gitversion.outputs.semVer }}
