name: build-tag-push

on: push

jobs:
  gitversion:
    name: Determine version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.getversion.outputs.version }}    
    container:
      image: gittools/gitversion:5.10.0-alpine.3.14-6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: getversion
        run: | 
          echo "version=$(/tools/dotnet-gitversion ${{ github.workspace }} /showvariable SemVer)" >> $GITHUB_OUTPUT

  version-check:
    runs-on: ubuntu-latest
    needs: gitversion
    steps:
      - if: ${{!needs.gitversion.outputs.version}}
        run: exit -1

  build-tag-push:
    name: "Build, tag and push"
    needs: [gitversion, version-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2        
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            voortman/talos-os-config-generator:latest
            voortman/talos-os-config-generator:${{needs.gitversion.outputs.version}}
