name: build-tag-push

on: push

jobs:
  gitversion:
    name: Determine version
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
      volumes:
        - ${{ github.workspace }}:/repo
    outputs:
      properties: ${{ steps.gitversion.outputs.properties }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GitVersion
        id: gitversion
        run: |
          export PATH="$PATH:/github/home/.dotnet/tools"
          dotnet tool install --global GitVersion.Tool --version 5.*
          cd /repo
          dotnet-gitversion /output buildserver
          cat $GITHUB_ENV
          echo 'properties<<EOF' >> $GITHUB_OUTPUT
          cat $GITHUB_ENV >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          
  build-tag-push:
    name: "Build, tag and push"
    needs: gitversion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '6.x'
#      - uses: gittools/actions/gitversion/setup@v0.9.14
#        with:
#          versionSpec: '5.x'
#      - uses: gittools/actions/gitversion/execute@v0.9.14
#        id: gitversion
      
      - uses: docker/setup-buildx-action@v2        

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            voortman/talos-os-config-generator:latest
            voortman/talos-os-config-generator:${{ needs.jobs.gitversion.outputs.properties.semVer }}
