name: Main

on: push
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
#        with:
#          useConfigFile: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            voortman/talos-os-config-generator:latest
            voortman/talos-os-config-generator:${{ $GitVersion_SemVer }}
